import { LitElement, PropertyValues } from 'lit';
export declare class ThyClock extends LitElement {
    size: number;
    dialColor: string;
    dialBackgroundColor: string;
    secondHandColor: string;
    minuteHandColor: string;
    hourHandColor: string;
    alarmHandColor: string;
    alarmHandTipColor: string;
    hideNumerals: boolean;
    numeralFont: string;
    brandFont: string;
    brandText?: string;
    brandText2?: string;
    tickingMinutes: boolean;
    sweepingSeconds: boolean;
    numerals: string;
    alarmTime?: string;
    timeOffsetOperator: string;
    timeOffsetHours: number;
    timeOffsetMinutes: number;
    private canvas?;
    private ctx?;
    private radius;
    private alarmTriggered;
    static styles: import("lit").CSSResult;
    firstUpdated(): void;
    updated(changedProperties: PropertyValues): void;
    render(): import("lit-html").TemplateResult<1>;
    private toRadians;
    private drawDial;
    private drawHand;
    private drawSecondHand;
    private drawMinuteHand;
    private drawHourHand;
    private twelveBased;
    private timeToDecimal;
    private drawAlarmHand;
    private checkAlarmTime;
    private last;
    private startClock;
}
